### PR TITLE
Fix password hashing when server has password enableb. fixes #68

### LINKED ISSUE #68: Error fetching job: Invalid password - password with invalid URL characters
Issue migrated from https://github.com/contribsys/faktory/issues/411

--------------

- Which Faktory package and version?
Faktory 1.6.1 Docker image (contribsys/faktory:1.6.1)

- Which Faktory worker package and version?
FWR 1.1.1

- Please include any relevant worker configuration

- Please include any relevant error messages or stacktraces
```
/usr/local/bundle/gems/faktory_worker_ruby-1.1.1/lib/faktory/client.rb:352:in `result': Invalid password\r (Faktory::CommandError)
	from /usr/local/bundle/gems/faktory_worker_ruby-1.1.1/lib/faktory/client.rb:362:in `ok'
	from /usr/local/bundle/gems/faktory_worker_ruby-1.1.1/lib/faktory/client.rb:294:in `open'
	from /usr/local/bundle/gems/faktory_worker_ruby-1.1.1/lib/faktory/client.rb:58:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
```

Are you using an old version? No

------------

I'm using Faktory docker image version 1.6.1 (contribsys/faktory:1.6.1) and FWR 1.1.1

When I set a password for Faktory (using the env var `FAKTORY_PASSWORD` on the server) and the password has an invalid URL character (eg: `@`), when I connect to the server with FWR, I get the invalid password error. If I use a password without any URL invalid characters, everything works fine.

In the FAKTORY_URL I used the url-encoded password. 

This docker compose file reproduces the error. If the password is changed to `password` (in both `FAKTORY_PASSWORD` and `FAKTORY_URL`), FWR can fetch jobs. 

```
version: '3'
services:
  faktory:
    image: contribsys/faktory
    environment:
      - FAKTORY_PASSWORD=p@ssword
    command: /faktory

  example:
    image: ruby:2.7.6
    depends_on: [faktory]
    environment:
      - FAKTORY_URL=tcp://:p%40ssword@faktory:7419
    command: bash -c "gem install faktory_worker_ruby && ruby -r faktory_worker_ruby -e Faktory::Client.new"
```

Maybe a url-decode is missing before computing the password hash??

### PR DESCRIPTION
**Pull request by ppires**
Fixes #68

### CODE REVIEW

**Comment by ppires** [comment]
@mperham The fix was very simple, but the test no so much.

I noticed that the test expext that the Faktory server is already running in the machine (did I missed something?).
If I start a server with passwrod enabled all tests fail except for the one I wrote. If the server has no password, only my test fails.

Do you have any suggestions to solve this problem?

**Comment by mperham** [comment]
Unfortunately the test suite is somewhat simple. It expects the server to be running with no password so jobs can be tested against a live server. We can change that to use a password by default so this code path is tested.

**Comment by mperham** [comment]
It's also possible that we just don't test this. The fact that you've tested it manually is sufficient.

**Comment by mperham** [comment]
See the test suite failure.

**Comment by mperham** [comment]
Ugh, this is way harder than it should be. I think you want `CGI.unescape`. This is not HTML form data but data that goes in a URI, like a CGI parameter.

**Pull request merged**
