### PR TITLE
Fix bid bleed

### PR DESCRIPTION
**Pull request by ffiller**
@mperham As discussed. Please let me know if you are happy with this test or if any additional context is needed to document for posterity.

### CODE REVIEW

**Comment by mperham** [comment]
I'm going to add a little more defensiveness to the code but this is a great start. Thanks again!

**Comment by ffiller** [comment]
Yeah, was thinking of tackling it in the Job module, but didn't want to send a huge PR. Can you release 1.0.3 once you're done? Thanks!

**Comment by mperham** [comment]
^^^^ There's my second pass at a fix. We need to ensure the problem is solved for any middleware so I dup before invoking the client middleware chain.

**Comment by mperham** [comment]
1.0.3 has been released. LMK how it works for you.

**Comment by ffiller** [comment]
@mperham Yes, that's a better fix. Works beautifully! Thanks again, and enjoy your week :)

**Pull request merged**
