### PR TITLE
Version bump to 0.7.1 - For ActiveJob adapter

### PR DESCRIPTION
**Pull request by jagthedrummer**
Would love to start using the AJ adapter in the wild.

### CODE REVIEW

**Comment by mperham** [comment]
I've added you as a collaborator.  You are welcome to bump the version yourself.  Don't forget to maintain the changelog with recent changes.

Also, if you have a rubygems account, I'd be happy to add you as a backup gem owner too just in case of emergency.

**Comment by jagthedrummer** [comment]
I just pushed an update to `Changes.md` to mention the adapter. I figure I'll make a wiki page about it, and another one about the testing stuff.

On a related note, I see the "Contributor" designation on my comments here, but it doesn't look like I have write access to the repo. (Maybe that's as intended and I misunderstood what you mean by "You are welcome to bump the version yourself".)

On rubygems I'm jagthedrumer AT gmail.com.

**Comment by mperham** [comment]
Read the collaboration email invite.

**Comment by mperham** [comment]
Did you spell your email right?  One m?

**Comment by jagthedrummer** [comment]
Oops, I did not spell it right, there are, in fact, 2 ms.

And I just found the invitation email that had been auto-sorted out of any of the folders I regularly check. Sorry for the confusion. Gonna merge this now.

Thanks!

**Comment by mperham** [comment]
Done and done!  Feel free to push 0.7.1 to rubygems with `rake release`.

**Comment by jagthedrummer** [comment]
Just pushed 0.7.1 and everything worked like a charm. Woot!

**Pull request merged**
